### ISSUE TITLE
Add instructions on how to run the project to the readme

### ISSUE THREAD

**Issue by akinsho** [FAC10/week-6-jajascript#52] opened 2017-03-31 09:17 UTC

**Comment by sohilpandya** [comment] 2017-03-31 09:38
@Akin909 please read through the existing list of issues that already exist and if there is nothing resembling what you've found only then create an issue. 

Don't want people to be dealing with duplicate issues.

**Comment by joeylouise** [comment] 2017-03-31 11:12
Duplicate of #49

**Closed as completed by joeylouise** 2017-03-31 11:12 UTC
